### ISSUE TITLE
Removing used css

### ISSUE THREAD

**Issue by CrashyBang** [purifycss/purifycss-webpack-plugin#62]
So I have the following css:

```css
body {
  display: -ms-flexbox;
  display: flex;
  background-color: deeppink; }
  body div {
    background-color: deepskyblue; }

p {
  background-color: lime; }
```

Which after purifying is looking like this:

```css
body {
  display: -ms-flexbox;
  display: flex;
  background-color: deeppink;
}

p {
  background-color: lime;
}
```

I am running with webpack 2.
